import 'package:flutter/material.dart';

/// Dropdown items for supported bank names.
final List<DropdownMenuItem<String>> bankNames = [
  const DropdownMenuItem(value: 'Askari Bank', child: Text('Askari Bank')),
  const DropdownMenuItem(value: 'Allied Bank Limited', child: Text('Allied Bank Limited')),
  const DropdownMenuItem(value: 'Bank Alfalah', child: Text('Bank Alfalah')),
  const DropdownMenuItem(value: 'Bank Al Habib', child: Text('Bank Al Habib')),
  const DropdownMenuItem(value: 'Faysal Bank', child: Text('Faysal Bank')),
  const DropdownMenuItem(value: 'Habib Bank Limited', child: Text('Habib Bank Limited')),
  const DropdownMenuItem(value: 'Habib Metropolitan Bank', child: Text('Habib Metropolitan Bank')),
  const DropdownMenuItem(value: 'JS Bank', child: Text('JS Bank')),
  const DropdownMenuItem(value: 'Samba Bank Limited', child: Text('Samba Bank Limited')),
  const DropdownMenuItem(value: 'Silkbank Limited', child: Text('Silkbank Limited')),
  const DropdownMenuItem(value: 'Standard Chartered Pakistan', child: Text('Standard Chartered Pakistan')),
  const DropdownMenuItem(value: 'Soneri Bank', child: Text('Soneri Bank')),
  const DropdownMenuItem(value: 'Summit Bank', child: Text('Summit Bank')),
  const DropdownMenuItem(value: 'United Bank Limited', child: Text('United Bank Limited')),
  const DropdownMenuItem(value: 'MCB Bank Limited', child: Text('MCB Bank Limited')),
  const DropdownMenuItem(value: 'Meezan Bank Limited', child: Text('Meezan Bank Limited')),
  const DropdownMenuItem(value: 'Soneri Mustaqeem Islamic Bank', child: Text('Soneri Mustaqeem Islamic Bank')),
  const DropdownMenuItem(value: 'Dubai Islamic Bank', child: Text('Dubai Islamic Bank')),
  const DropdownMenuItem(value: 'Al Baraka Bank', child: Text('Al Baraka Bank')),
  const DropdownMenuItem(value: 'Bank Alfalah Islamic', child: Text('Bank Alfalah Islamic')),
  const DropdownMenuItem(value: 'BankIslami Pakistan Limited', child: Text('BankIslami Pakistan Limited')),
  const DropdownMenuItem(value: 'Askari Bank Ltd', child: Text('Askari Bank Ltd')),
  const DropdownMenuItem(value: 'MCB Islamic Banking', child: Text('MCB Islamic Banking')),
  const DropdownMenuItem(value: 'UBL Islamic Banking', child: Text('UBL Islamic Banking')),
  const DropdownMenuItem(value: 'HBL Islamic Banking', child: Text('HBL Islamic Banking')),
  const DropdownMenuItem(value: 'National Bank of Pakistan', child: Text('National Bank of Pakistan')),
  const DropdownMenuItem(value: 'Bank Al Habib Islamic Banking', child: Text('Bank Al Habib Islamic Banking')),
  const DropdownMenuItem(value: 'Bank of Punjab Islamic Banking', child: Text('Bank of Punjab Islamic Banking')),
  const DropdownMenuItem(value: 'Allied Islamic Bank', child: Text('Allied Islamic Bank')),
  const DropdownMenuItem(value: 'Faysal Bank (Islamic)', child: Text('Faysal Bank (Islamic)')),
  const DropdownMenuItem(value: 'HabibMetro (Sirat Islamic Banking)', child: Text('HabibMetro (Sirat Islamic Banking)')),
  const DropdownMenuItem(value: 'Silk Bank (Emaan Islamic Banking)', child: Text('Silk Bank (Emaan Islamic Banking)')),
  const DropdownMenuItem(value: 'Advans Microfinance Bank', child: Text('Advans Microfinance Bank')),
  const DropdownMenuItem(value: 'Finca Microfinance Bank', child: Text('Finca Microfinance Bank')),
  const DropdownMenuItem(value: 'ASA Pakistan Microfinance', child: Text('ASA Pakistan Microfinance')),
  const DropdownMenuItem(value: 'First Microfinance Bank', child: Text('First Microfinance Bank')),
  const DropdownMenuItem(value: 'Khushhali Microfinance Bank', child: Text('Khushhali Microfinance Bank')),
  const DropdownMenuItem(value: 'NRSP Microfinance Bank', child: Text('NRSP Microfinance Bank')),
  const DropdownMenuItem(value: 'Telenor Microfinance Bank', child: Text('Telenor Microfinance Bank')),
  const DropdownMenuItem(value: 'Apna Microfinance Bank', child: Text('Apna Microfinance Bank')),
  const DropdownMenuItem(value: 'Mobilink Microfinance Bank', child: Text('Mobilink Microfinance Bank')),
  const DropdownMenuItem(value: 'Pak-Oman Microfinance Bank', child: Text('Pak-Oman Microfinance Bank')),
  const DropdownMenuItem(value: 'Sindh Microfinance Bank (SMFB)', child: Text('Sindh Microfinance Bank (SMFB)')),
  const DropdownMenuItem(value: 'U Microfinance Bank', child: Text('U Microfinance Bank')),
  const DropdownMenuItem(value: 'Akhuwat (Microfinance)', child: Text('Akhuwat (Microfinance)')),
  const DropdownMenuItem(value: 'Deutsche Bank AG', child: Text('Deutsche Bank AG')),
  const DropdownMenuItem(value: 'Citi Bank N.A', child: Text('Citi Bank N.A')),
  const DropdownMenuItem(value: 'Industrial and Commercial Bank of China Limited', child: Text('Industrial and Commercial Bank of China Limited')),
  const DropdownMenuItem(value: 'Bank of China', child: Text('Bank of China')),
  const DropdownMenuItem(value: 'Other', child: Text('Other')),
];
